//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login_MVC_Project_2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class C_User
    {
        public int UserID { get; set; }
        [DisplayName("User Name:")]
        [Required(ErrorMessage ="Please Enter Username!")]
        public string UserName { get; set; }
        [DisplayName("Password:")]
        [DataType(DataType.Password)] //Set password input
        [Required(ErrorMessage = "Please Enter Password!")]
        public string Password { get; set; }

        public string LoginErrorMessage { get; set; }
    }
}
